// Package templates provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package templates

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for Active.
const (
	ActiveN0 Active = 0
	ActiveN1 Active = 1
)

// Defines values for Active1.
const (
	Active1N0 Active1 = 0
	Active1N1 Active1 = 1
)

// Defines values for Editor.
const (
	EditorCode   Editor = "code"
	EditorDesign Editor = "design"
)

// Defines values for Editor1.
const (
	Editor1Code   Editor1 = "code"
	Editor1Design Editor1 = "design"
)

// Defines values for Generation.
const (
	GenerationDynamic Generation = "dynamic"
	GenerationLegacy  Generation = "legacy"
)

// Defines values for Generation1.
const (
	Generation1Dynamic Generation1 = "dynamic"
	Generation1Legacy  Generation1 = "legacy"
)

// Defines values for Generations.
const (
	Dynamic       Generations = "dynamic"
	Legacy        Generations = "legacy"
	LegacyDynamic Generations = "legacy,dynamic"
)

// Active defines model for Active.
type Active int

// Active1 defines model for Active1.
type Active1 int

// Editor defines model for Editor.
type Editor string

// Editor1 defines model for Editor1.
type Editor1 string

// Generation defines model for Generation.
type Generation string

// Generation1 defines model for Generation1.
type Generation1 string

// Generations defines model for Generations.
type Generations string

// Metadata defines model for Metadata.
type Metadata struct {
	Count *int    `json:"count,omitempty"`
	Next  *string `json:"next,omitempty"`
	Prev  *string `json:"prev,omitempty"`
	Self  *string `json:"self,omitempty"`
}

// TransactionalTemplate defines model for TransactionalTemplate.
type TransactionalTemplate struct {
	Generation Generation1 `json:"generation"`

	// ID The ID of the transactional template.
	ID string `json:"id"`

	// Name The name for the transactional template.
	Name string `json:"name"`

	// UpdatedAt The date and time that this transactional template version was updated.
	UpdatedAt string `json:"updated_at"`

	// Versions The different versions of this transactional template.
	Versions *[]TransactionalTemplatesVersionOutputLean `json:"versions,omitempty"`
	Warning  *TransactionalTemplateWarning              `json:"warning,omitempty"`
}

// TransactionalTemplateVersionCreate defines model for TransactionalTemplateVersionCreate.
type TransactionalTemplateVersionCreate struct {
	Active *Active `json:"active,omitempty"`
	Editor *Editor `json:"editor,omitempty"`

	// GeneratePlainContent If true, plain_content is always generated from html_content. If false, plain_content is not altered.
	GeneratePlainContent *bool `json:"generate_plain_content,omitempty"`

	// HTMLContent The HTML content of the version. Maximum of 1048576 bytes allowed.
	HTMLContent *string `json:"html_content,omitempty"`

	// Name Name of the transactional template version.
	Name string `json:"name"`

	// PlainContent Text/plain content of the transactional template version. Maximum of 1048576 bytes allowed.
	PlainContent *string `json:"plain_content,omitempty"`

	// Subject Subject of the new transactional template version.
	Subject string `json:"subject"`

	// TestData For dynamic templates only, the mock json data that will be used for template preview and test sends.
	TestData *string `json:"test_data,omitempty"`
}

// TransactionalTemplateVersionOutput defines model for TransactionalTemplateVersionOutput.
type TransactionalTemplateVersionOutput struct {
	Active *Active1 `json:"active,omitempty"`
	Editor *Editor1 `json:"editor,omitempty"`

	// GeneratePlainContent If true, plain_content is always generated from html_content. If false, plain_content is not altered.
	GeneratePlainContent *bool `json:"generate_plain_content,omitempty"`

	// HTMLContent The HTML content of the Design.
	HTMLContent *string `json:"html_content,omitempty"`

	// ID ID of the transactional template version.
	ID *string `json:"id,omitempty"`

	// Name Name of the transactional template version.
	Name string `json:"name"`

	// PlainContent Plain text content of the Design.
	PlainContent *string `json:"plain_content,omitempty"`

	// Subject Subject of the new transactional template version.
	Subject string `json:"subject"`

	// TemplateID ID of the transactional template.
	TemplateID *string `json:"template_id,omitempty"`

	// TestData For dynamic templates only, the mock json data that will be used for template preview and test sends.
	TestData *string `json:"test_data,omitempty"`

	// ThumbnailURL A Thumbnail preview of the template's html content.
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`

	// UpdatedAt The date and time that this transactional template version was updated.
	UpdatedAt *string                         `json:"updated_at,omitempty"`
	Warnings  *[]TransactionalTemplateWarning `json:"warnings,omitempty"`
}

// TransactionalTemplateWarning defines model for TransactionalTemplateWarning.
type TransactionalTemplateWarning struct {
	// Message Warning message for the user
	Message *string `json:"message,omitempty"`
}

// TransactionalTemplatesTemplateLean defines model for TransactionalTemplatesTemplateLean.
type TransactionalTemplatesTemplateLean struct {
	Generation Generation1 `json:"generation"`

	// ID The ID of the transactional template.
	ID openapi_types.UUID `json:"id"`

	// Name The name for the transactional template.
	Name string `json:"name"`

	// UpdatedAt The date and time that this transactional template version was updated.
	UpdatedAt string `json:"updated_at"`

	// Versions The different versions of this transactional template.
	Versions *[]TransactionalTemplatesVersionOutputLean `json:"versions,omitempty"`
}

// TransactionalTemplatesVersionOutputLean defines model for TransactionalTemplatesVersionOutputLean.
type TransactionalTemplatesVersionOutputLean struct {
	Active *Active1 `json:"active,omitempty"`
	Editor *Editor1 `json:"editor,omitempty"`

	// GeneratePlainContent If true, plain_content is always generated from html_content. If false, plain_content is not altered.
	GeneratePlainContent *bool `json:"generate_plain_content,omitempty"`

	// HTMLContent The HTML content of the Design.
	HTMLContent *string `json:"html_content,omitempty"`

	// ID ID of the transactional template version.
	ID *string `json:"id,omitempty"`

	// Name Name of the transactional template version.
	Name *string `json:"name,omitempty"`

	// PlainContent Plain text content of the Design.
	PlainContent *string `json:"plain_content,omitempty"`

	// Subject Subject of the new transactional template version.
	Subject *string `json:"subject,omitempty"`

	// TemplateID ID of the transactional template.
	TemplateID *string `json:"template_id,omitempty"`

	// ThumbnailURL A Thumbnail preview of the template's html content.
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`

	// UpdatedAt The date and time that this transactional template version was updated.
	UpdatedAt *string `json:"updated_at,omitempty"`
}

// OnBehalfOf defines model for OnBehalfOf.
type OnBehalfOf = string

// PostPatchTransactionalTemplateVersion defines model for PostPatchTransactionalTemplateVersion.
type PostPatchTransactionalTemplateVersion = TransactionalTemplateVersionCreate

// ListTemplateParams defines parameters for ListTemplate.
type ListTemplateParams struct {
	// Generations Comma-delimited list specifying which generations of templates to return. Options are `legacy`, `dynamic` or `legacy,dynamic`.
	Generations *Generations `form:"generations,omitempty" json:"generations,omitempty"`

	// PageSize The number of templates to be returned in each page of results
	PageSize float32 `form:"page_size" json:"page_size"`

	// PageToken A token corresponding to a specific page of results, as provided by metadata
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`

	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// CreateTemplateJSONBody defines parameters for CreateTemplate.
type CreateTemplateJSONBody struct {
	Generation *Generation `json:"generation,omitempty"`

	// Name The name for the new transactional template.
	Name string `json:"name"`
}

// CreateTemplateParams defines parameters for CreateTemplate.
type CreateTemplateParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// DeleteTemplateParams defines parameters for DeleteTemplate.
type DeleteTemplateParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// GetTemplateParams defines parameters for GetTemplate.
type GetTemplateParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// UpdateTemplateJSONBody defines parameters for UpdateTemplate.
type UpdateTemplateJSONBody struct {
	// Name The name of the transactional template.
	Name *string `json:"name,omitempty"`
}

// UpdateTemplateParams defines parameters for UpdateTemplate.
type UpdateTemplateParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// DuplicateTemplateJSONBody defines parameters for DuplicateTemplate.
type DuplicateTemplateJSONBody struct {
	// Name The name for the new transactional template.
	Name *string `json:"name,omitempty"`
}

// DuplicateTemplateParams defines parameters for DuplicateTemplate.
type DuplicateTemplateParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// CreateTemplateVersionParams defines parameters for CreateTemplateVersion.
type CreateTemplateVersionParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// DeleteTemplateVersionParams defines parameters for DeleteTemplateVersion.
type DeleteTemplateVersionParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// GetTemplateVersionParams defines parameters for GetTemplateVersion.
type GetTemplateVersionParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// UpdateTemplateVersionParams defines parameters for UpdateTemplateVersion.
type UpdateTemplateVersionParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// ActivateTemplateVersionParams defines parameters for ActivateTemplateVersion.
type ActivateTemplateVersionParams struct {
	// OnBehalfOf The `on-behalf-of` header allows you to make API calls from a parent account on behalf of the parent's Subusers or customer accounts. You will use the parent account's API key when using this header. When making a call on behalf of a customer account, the property value should be "account-id" followed by the customer account's ID (e.g., `on-behalf-of: account-id <account-id>`). When making a call on behalf of a Subuser, the property value should be the Subuser's username (e.g., `on-behalf-of: <subuser-username>`). See [**On Behalf Of**](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/on-behalf-of) for more information.
	OnBehalfOf *OnBehalfOf `json:"on-behalf-of,omitempty"`
}

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody CreateTemplateJSONBody

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody UpdateTemplateJSONBody

// DuplicateTemplateJSONRequestBody defines body for DuplicateTemplate for application/json ContentType.
type DuplicateTemplateJSONRequestBody DuplicateTemplateJSONBody

// CreateTemplateVersionJSONRequestBody defines body for CreateTemplateVersion for application/json ContentType.
type CreateTemplateVersionJSONRequestBody = TransactionalTemplateVersionCreate

// UpdateTemplateVersionJSONRequestBody defines body for UpdateTemplateVersion for application/json ContentType.
type UpdateTemplateVersionJSONRequestBody = TransactionalTemplateVersionCreate
